"""Render the cloud-init files Raspberry Pi OS (Trixie and later) reads on
first boot. Raspberry Pi Imager 2.x writes these itself in the GUI; in --cli
mode it takes ours via --cloudinit-userdata / --cloudinit-networkconfig.

The shape follows what Imager generates (users, enable_ssh, rpi.interfaces)
plus what we add: /etc/bird-listener/node.env and a first-boot command that
clones the repo and runs install.sh.
"""
from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import dataclass, field

USER_GROUPS = ("users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,"
               "gpio,spi,i2c,render,sudo")


def q(s: str) -> str:
    """A YAML-safe double-quoted scalar (JSON strings are valid YAML)."""
    return json.dumps(str(s))


def hash_password(plain: str) -> str | None:
    """SHA-512 crypt via openssl (present on macOS and Linux). None if unavailable."""
    if not shutil.which("openssl"):
        return None
    p = subprocess.run(["openssl", "passwd", "-6", "-stdin"], input=plain + "\n",
                       capture_output=True, text=True)
    return p.stdout.strip() if p.returncode == 0 and p.stdout.startswith("$6$") else None


@dataclass
class NodePlan:
    node: str                    # "window" | "wall"
    hostname: str
    user: str
    password: str
    ssh_pubkey: str
    timezone: str
    wifi_ssid: str
    wifi_password: str
    country: str                 # ISO alpha-2 for the WiFi regulatory domain
    node_env: dict[str, str]     # written to /etc/bird-listener/node.env
    repo_url: str
    repo_ref: str
    extra_packages: list[str] = field(default_factory=list)


def render_user_data(p: NodePlan) -> str:
    hashed = hash_password(p.password)
    if hashed:
        pw_lines = [f"    passwd: {q(hashed)}"]
    else:
        pw_lines = [f"    plain_text_passwd: {q(p.password)}"]
    env_body = "\n".join(f"      {k}={v}" for k, v in p.node_env.items())
    interfaces = ["    serial: false"]
    if p.node == "wall":
        interfaces = ["    spi: true", "    i2c: true", "    serial: false"]
    packages = ["avahi-daemon", "git", "curl"] + list(p.extra_packages)

    bootstrap = (
        f"git clone --depth 1 --branch {p.repo_ref} {p.repo_url} /opt/bird-listener-bootstrap "
        f"&& bash /opt/bird-listener-bootstrap/install.sh"
    )
    lines = [
        "#cloud-config",
        "# Generated by `birdlistener flash`. Read once by cloud-init on first boot.",
        "manage_resolv_conf: false",
        "",
        f"hostname: {q(p.hostname)}",
        "manage_etc_hosts: true",
        f"timezone: {q(p.timezone)}",
        "packages:",
        *[f"  - {pkg}" for pkg in packages],
        "apt:",
        "  preserve_sources_list: true",
        "  conf: |",
        "    Acquire {",
        '      Check-Date "false";',
        "    };",
        "keyboard:",
        "  model: pc105",
        '  layout: "us"',
        "users:",
        f"  - name: {q(p.user)}",
        f"    groups: {USER_GROUPS}",
        "    shell: /bin/bash",
        "    lock_passwd: false",
        *pw_lines,
        "    ssh_authorized_keys:",
        f"      - {q(p.ssh_pubkey)}",
        "    sudo: ALL=(ALL) NOPASSWD:ALL",
        "enable_ssh: true",
        "ssh_pwauth: false",
        "rpi:",
        "  interfaces:",
        *interfaces,
        "write_files:",
        "  - path: /etc/bird-listener/node.env",
        "    owner: root:root",
        "    permissions: '0600'",
        "    content: |",
        env_body,
        "runcmd:",
        f"  - [bash, -lc, {q(bootstrap + ' >> /var/log/bird-listener-firstboot.log 2>&1')}]",
        "",
    ]
    return "\n".join(lines)


def render_network_config(p: NodePlan) -> str:
    lines = [
        "network:",
        "  version: 2",
        "  ethernets:",
        "    eth0:",
        "      dhcp4: true",
        "      dhcp6: true",
        "      optional: true",
        "  wifis:",
        "    wlan0:",
        "      dhcp4: true",
        f"      regulatory-domain: {q(p.country)}",
        "      access-points:",
        f"        {q(p.wifi_ssid)}:",
        f"          password: {q(p.wifi_password)}",
        "      optional: true",
        "",
    ]
    return "\n".join(lines)


def render_meta_data(p: NodePlan, instance_id: str) -> str:
    return f"instance-id: {instance_id}\nlocal-hostname: {p.hostname}\n"
